#server:
#  port: 5050

#### thymeleaf Setting
#thymeleaf:
#  mode: HTML
#  prefix: classpath:templates/
#  suffix: .html
#  cache: false
#  check-template-location: true
#  character-encoding: UTF-8

### Application Setting
spring:
  application:
    name: kopring-basic-app
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

# Statistics Logger
logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
