server:
  port: 5050

### thymeleaf Setting
thymeleaf:
  mode: HTML
  prefix: classpath:templates/
  suffix: .html
  cache: false
  check-template-location: true
  character-encoding: UTF-8

### Application Setting
spring:
  application:
    name: kopring-basic-app
  jpa:
    # Show Console SQL Query
    show-sql: true
    hibernate:
      ddl-auto:  create-drop
      # format SQL Logger
      format_sql: true
      # Hibernate Statistics Logger
      properties:
        hibernate:
          generate_statistics: true

# Statistics Logger
logging:
  level:
    org:
      hibernate:
        stat: debug
