version: '3'
services:
  mysql_kotlin_core:
    image: arm64v8/mysql
    container_name: mysql_kotlin_core
    restart: always
    ports:
      - "23306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db1/mysql:/var/lib/mysqlysql
      # init.sql
      - ./db1/sql:/docker-entrypoint-initdb.d
  redis_kotlin_core:
      image: redis:latest
      container_name: redis_kotlin_core
      ports:
          - 6379:6379
      volumes:
          - ./redis/data:/data
          - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
      labels:
          - "name=redis"
          - "mode=standalone" # redis mode
      restart: always
      command: redis-server /usr/local/conf/redis.conf
